DROP TABLE IF EXISTS users1;
DROP SEQUENCE IF EXISTS global_seq1;
CREATE SEQUENCE global_seq1 START 10000;

CREATE TABLE users1(
id INTEGER PRIMARY KEY DEFAULT nextval('global_seq'),
name VARCHAR (45) NOT NULL,
lastName VARCHAR(45) NOT NULL

)

